environment:
  matrix:
    - PYTHON_VERSION: 2.7

install:
  - choco install miniconda3
  - conda create -n %PYTHON_VERSION% python=%PYTHON_VERSION%
  - activate %PYTHON_VERSION%

build: false

test_script:
  - python --version
